### PR TITLE
update for comonad 4.0 generalized cohoist

### PR DESCRIPTION
**Pull request by markwright**
You may want to tweak the dependencies a little more.  Tested with latest versions of the dependencies.

### CODE REVIEW

**Comment by finlay** [comment]
Thanks Mark

I found this bug from a fresh install of Edward's (great) algebra package.

I'll pull from here, but would be good to have it merged and pushed to hackage.

F

**Comment by nomeata** [comment]
JFR: Am I right to assume that this will hit hackage around the same time https://github.com/ekmett/adjunctions/issues/3 is being fixed?

**Comment by ekmett** [comment]
Yeah this is part of `adjunctions` and `representable-functors` merging. =/

**Comment by nomeata** [comment]
Obviously. Sorry for losing oversight of all the many packages sometimes, and poking at them individually.

**Comment by ekmett** [comment]
It is more than okay. If there is anything I can do that makes your job easier, feel free to ask.

**Pull request merged**
